xcopy /q /y  "App_Data" "PDF\App_Data\"
xcopy /q /y  "App_Data\PDF" "PDF\App_Data\PDF\"
xcopy /q /y  "App_Data\Data" "PDF\App_Data\Data\"
xcopy /q /y  "App_Start" "PDF\App_Start\"
xcopy /q /y   "Content" "PDF\Content\"
xcopy /q /y /s "Content\PDF" "PDF\Content\PDF\"
xcopy /q /y /s "Content\PdfViewer" "PDF\Content\PdfViewer\"
xcopy /q /y /s "Content\images" "PDF\Content\images\"
xcopy /q /y /s "Content\styles" "PDF\Content\styles\"
xcopy /q /y  "Controllers" "PDF\Controllers\"
xcopy /q /y /s "Controllers\PDF" "PDF\Controllers\PDF\"
xcopy /q /y  "Controllers\PdfViewer" "PDF\Controllers\PdfViewer\"
xcopy /q /y  "Controllers\HomeController.cs" "PDF\Controllers\"
xcopy /q /y  "Controllers\ScheduleHub.cs" "PDF\Controllers\"
xcopy /q /y  "CustomAttributes" "PDF\CustomAttributes\"
xcopy /q /y  "Helpers" "PDF\Helpers\"
xcopy /q /y  "Models\FindPDFCorruptionMessage.cs" "PDF\Models\"
xcopy /q /y  "Models\ProgrammaticOperationsModel.cs" "PDF\Models\"
xcopy /q /y  "Models\SignatureValidationMessage.cs" "PDF\Models\"
xcopy /q /y  "Properties" "PDF\Properties\"
xcopy /q /y  "Properties\PublishProfiles" "PDF\Properties\PublishProfiles\"
xcopy /q /y  "Scripts" "PDF\Scripts\"
xcopy /q /y /s "Scripts\cldr-data" "PDF\Scripts\cldr-data\"
xcopy /q /y  "Scripts\locale" "PDF\Scripts\locale\"
xcopy /q /y  "Views" "PDF\Views\"
xcopy /q /y  "Views\PDF" "PDF\Views\PDF\"
xcopy /q /y  "Views\PdfViewer" "PDF\Views\PdfViewer\"
xcopy /q /y  "Views\Shared" "PDF\Views\Shared\"
xcopy /q /y  "Views\_ViewStart.cshtml" "PDF\Views\"
xcopy /q /y  "Views\Web.config" "PDF\Views\"
xcopy /q /y  "webapi\PdfViewer" "PDF\webapi\PdfViewer\"
xcopy /q /y  ".deployment" "PDF\"
xcopy /q /y  ".gitignore" "PDF\"
xcopy /q /y  ".gitleaksignore" "PDF\"
xcopy /q /y  ".npmrc" "PDF\"
xcopy /q /y  "ApplicationInsights.config" "PDF\"
xcopy /q /y  "config.json" "PDF\"
xcopy /q /y  "deploy" "PDF\"
xcopy /q /y  "favicon.ico" "PDF\"
xcopy /q /y  "Global.asax" "PDF\"
xcopy /q /y  "Global.asax.cs" "PDF\"
xcopy /q /y  "gulpfile.js" "PDF\"
xcopy /q /y  "Jenkinsfile" "PDF\"
xcopy /q /y  "NuGet.config" "PDF\"
xcopy /q /y  "package.json" "PDF\"
xcopy /q /y  "Project_Readme.html" "PDF\"
xcopy /q /y  "README.md" "PDF\"
xcopy /q /y  "Startup.cs" "PDF\"
xcopy /q /y  "SyncfusionLicense.txt" "PDF\"
xcopy /q /y  "Web.config" "PDF\"
xcopy /q /y  "Web.Debug.config" "PDF\"
xcopy /q /y  "Web.Release.config" "PDF\"
xcopy /q /y "PDF\samplelist.js" "PDF\scripts\"
xcopy /q /y "PDF\sampleOrder.json" "PDF\scripts\"


@echo off
set "destinationFile=PDF\Controllers\HomeController.cs"
set "searchWord=RedirectToAction("gridoverview", "grid")"
set "replaceWord=RedirectToAction("default", "pdf")"

setlocal enabledelayedexpansion
(for /f "usebackq delims=" %%a in ("%destinationFile%") do (
    set "line=%%a"
    set "line=!line:%searchWord%=%replaceWord%!"
    echo !line!
)) > "%destinationFile%.tmp"

move /y "%destinationFile%.tmp" "%destinationFile%"

echo Word '%searchWord%' replaced with '%replaceWord%' in %destinationFile%